# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87ce48550689fcd8bf83b89cf2384c1813c2591295df49b0b4e275f6afdf188b601a429f2145709ec530f3fffe687119d69e64b9d3e65333d29242712282a143

test:
  secret_key_base: e388c690b353419a25edf4c090642350608bd4ff3d559eeef0751c8725408a5a0c7520ed81d0915f9feefa14adf88b4e5e7e7952b4265e03aa4223392b6c083d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
